import type { Metadata } from "next";
import { MenuResponsive } from "@/pages/setMenuResponse";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <MenuResponsive />
      {children}
      <footer className="fixed bottom-0">aaa</footer>
    </>
  );
}
